# Generated by Django 3.0.6 on 2020-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, default='описание', max_length=50, null=True, verbose_name='Фото'),
        ),
    ]
