# Generated by Django 3.0.6 on 2020-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/avatar.png', upload_to='profiles/', verbose_name='Avatar'),
        ),
    ]
