# Generated by Django 3.0.6 on 2020-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200508_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/avatar.png', null=True, upload_to='profiles/', verbose_name='Avatar'),
        ),
    ]
